export const SWITCH_BLUE = 'SWITCH_BLUE';
export const SWITCH_PURPLE = 'SWITCH_PURPLE';
export const SWITCH_GREEN = 'SWITCH_GREEN';
export const SWITCH_RED = 'SWITCH_RED';
export const SWITCH_BLACK = 'SWITCH_BLACK';
export const SWITCH_WHITE = 'SWITCH_WHITE';
export const SWITCH_SIDE = 'SWITCH_SIDE';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CHANGE_FONT_SIZE = 'CHANGE_FONT_SIZE';
export const CHANGE_TEXT_COLOR = 'CHANGE_TEXT_COLOR';
export const SHOW_TEXT_SETTINGS = 'SHOW_TEXT_SETTINGS';
export const SHOW_IMAGE_SETTINGS = 'SHOW_IMAGE_SETTINGS';
export const CHANGE_IMG = 'CHANGE_IMG';

